### PR TITLE
Hungarian Translation!

### PR DESCRIPTION
**Pull request by kispintyi**
Hungarian Translation!

### CODE REVIEW

**Comment by anastarawneh** [comment]
Not gonna lie, I've never dealt with pull requests before lol, pretty sure I merged it correctly. Thank you!

**Comment by kispintyi** [comment]
I hope so, it's alright! :D I don't know it either (how to use one single pull request for example, I still don't know for 100%)

**Comment by kispintyi** [comment]
btw. Can I have your Discord please?

**Comment by anastarawneh** [comment]
My Discord is Anas#4896, and you can join the mod section of my Discord server through this link: https://discord.gg/4XyWdWzRrU.

**Pull request merged**
